### PR TITLE
use array_merge in place of ...$sdk

### LINKED ISSUE #10: Fatal error: Uncaught Error: Cannot unpack array with string keys
https://github.com/newfold-labs/wp-module-runtime/blob/9de4f765c12194c7356c2fbaf8182a56d9ba4433/includes/Runtime.php#L58

This causes errors in PHP 8.0 and below. We have many customers on PHP 7.x and 8.0 so we can't use this splat operator. It causes a fatal error in WordPress and crashes any site on older PHP versions.

Fatal error: Uncaught Error: Cannot unpack array with string keys in /wp-content/plugins/bluehost-wordpress-plugin/vendor/newfold-labs/wp-module-runtime/includes/Runtime.php:58

### PR DESCRIPTION
**Pull request by circlecube**
with php<8.1 this splat operator (...) cannot work with an associative array and causes a fatal error.

fixes #10

### CODE REVIEW

**Comment by wpscholar** [comment]
@circlecube Haha! See https://github.com/newfold-labs/wp-module-runtime/pull/9

File: includes/Runtime.php [hunk 1]
```diff
@@ -39,23 +39,25 @@ public function loadIntoPage( $page ) {
...
-			'homeUrl'     => \get_home_url(),
-			'capabilities' => $this->container->get( 'capabilities' )->all(),
-			'sdk'          => $sdk, // kept for backward compatability, will be removed later
-			'siteUrl'		=> \get_site_url(),
-			'siteTitle' => htmlspecialchars_decode( \get_bloginfo( 'name' ) ),
-			'restUrl' 	=> \esc_url_raw( \get_home_url() . '/index.php?rest_route=' ),
-			'restNonce'			=> wp_create_nonce('wp-rest'),
-			'isWoocommerceActive' 	=> is_plugin_active('woocommerce/woocommerce.php'),
-			...$sdk
+		return array_merge(
```
Comment (wpscholar) [inline includes/Runtime.php:42]: @circlecube We should dispose of the array merge part. There's no need to duplicate the SDK contents into the root. We should manually add the `wpversion` attribute to the root (but name it `wpVersion` instead).

**Review by wpscholar — CHANGES_REQUESTED** [review]

**Review by wpscholar — APPROVED** [review]
